env_file:
  - .env/dockerpasswords.txt

version: '3.1'

services:
  app:
    build: .
    depends_on:
    - db
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:example@db/flask'

  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
